"use strict";
/**
 * Yum Food Orders
 * **Yum application, order food daily from the best chef in town**  This API is used by the angular.io client, and is not meant to be used otherwise.  Find source code of this API [here](https://github.com/jrtdev/yum)  Copyright (C) 2017 JR Technologies.     ------------------------------------      Last edit: 28/09/2017 10:00  -------------------------------------
 *
 * OpenAPI spec version: 1.2.8
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiRGFpbHlNZW51LmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiRGFpbHlNZW51LnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQTs7Ozs7Ozs7OztHQVVHIiwic291cmNlc0NvbnRlbnQiOlsiLyoqXHJcbiAqIFl1bSBGb29kIE9yZGVyc1xyXG4gKiAqKll1bSBhcHBsaWNhdGlvbiwgb3JkZXIgZm9vZCBkYWlseSBmcm9tIHRoZSBiZXN0IGNoZWYgaW4gdG93bioqICBUaGlzIEFQSSBpcyB1c2VkIGJ5IHRoZSBhbmd1bGFyLmlvIGNsaWVudCwgYW5kIGlzIG5vdCBtZWFudCB0byBiZSB1c2VkIG90aGVyd2lzZS4gIEZpbmQgc291cmNlIGNvZGUgb2YgdGhpcyBBUEkgW2hlcmVdKGh0dHBzOi8vZ2l0aHViLmNvbS9qcnRkZXYveXVtKSAgQ29weXJpZ2h0IChDKSAyMDE3IEpSIFRlY2hub2xvZ2llcy4gICAgIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSAgICAgIExhc3QgZWRpdDogMjgvMDkvMjAxNyAxMDowMCAgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSBcclxuICpcclxuICogT3BlbkFQSSBzcGVjIHZlcnNpb246IDEuMi44XHJcbiAqIFxyXG4gKlxyXG4gKiBOT1RFOiBUaGlzIGNsYXNzIGlzIGF1dG8gZ2VuZXJhdGVkIGJ5IHRoZSBzd2FnZ2VyIGNvZGUgZ2VuZXJhdG9yIHByb2dyYW0uXHJcbiAqIGh0dHBzOi8vZ2l0aHViLmNvbS9zd2FnZ2VyLWFwaS9zd2FnZ2VyLWNvZGVnZW4uZ2l0XHJcbiAqIERvIG5vdCBlZGl0IHRoZSBjbGFzcyBtYW51YWxseS5cclxuICovXHJcblxyXG5pbXBvcnQgKiBhcyBtb2RlbHMgZnJvbSAnLi9tb2RlbHMnO1xyXG5cclxuLyoqXHJcbiAqIEEgZGFpbHkgTWVudSwgIGhhcyBvcmRlciBjaGVja2VkIERUT1xyXG4gKi9cclxuZXhwb3J0IGludGVyZmFjZSBEYWlseU1lbnUge1xyXG4gICAgaWQ/OiBudW1iZXI7XHJcblxyXG4gICAgZGF0ZT86IERhdGU7XHJcblxyXG4gICAgb3JkZXJJZD86IG51bWJlcjtcclxuXHJcbiAgICBpc0ZpbmFsPzogYm9vbGVhbjtcclxuXHJcbiAgICBsYXN0T3JkZXJEYXRlVGltZT86IERhdGU7XHJcblxyXG4gICAgY29tbWVudD86IHN0cmluZztcclxuXHJcbiAgICBmb29kcz86IEFycmF5PG1vZGVscy5Gb29kV2l0aFF1YW50aXR5PjtcclxuXHJcbiAgICBsYXN0RWRpdD86IG1vZGVscy5MYXN0RWRpdDtcclxuXHJcbiAgICB0b3RhbFByaWNlPzogbnVtYmVyO1xyXG5cclxuICAgIGJhbGFuY2U/OiBudW1iZXI7XHJcblxyXG59XHJcbiJdfQ==