"use strict";
/**
 * Yum Food Orders
 * **Yum application, order food daily from the best chef in town**  This API is used by the angular.io client, and is not meant to be used otherwise.  Find source code of this API [here](http://gitlab/)  Copyright (C) 2017 JR Technologies.     ------------------------------------       Last edit: 21/04/2017 15:00   -------------------------------------
 *
 * OpenAPI spec version: 1.0.7
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiRGFpbHlNZW51RWRpdC5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIkRhaWx5TWVudUVkaXQudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBOzs7Ozs7Ozs7O0dBVUciLCJzb3VyY2VzQ29udGVudCI6WyIvKipcclxuICogWXVtIEZvb2QgT3JkZXJzXHJcbiAqICoqWXVtIGFwcGxpY2F0aW9uLCBvcmRlciBmb29kIGRhaWx5IGZyb20gdGhlIGJlc3QgY2hlZiBpbiB0b3duKiogIFRoaXMgQVBJIGlzIHVzZWQgYnkgdGhlIGFuZ3VsYXIuaW8gY2xpZW50LCBhbmQgaXMgbm90IG1lYW50IHRvIGJlIHVzZWQgb3RoZXJ3aXNlLiAgRmluZCBzb3VyY2UgY29kZSBvZiB0aGlzIEFQSSBbaGVyZV0oaHR0cDovL2dpdGxhYi8pICBDb3B5cmlnaHQgKEMpIDIwMTcgSlIgVGVjaG5vbG9naWVzLiAgICAgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tICAgICAgIExhc3QgZWRpdDogMjEvMDQvMjAxNyAxNTowMCAgIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS1cclxuICpcclxuICogT3BlbkFQSSBzcGVjIHZlcnNpb246IDEuMC43XHJcbiAqXHJcbiAqXHJcbiAqIE5PVEU6IFRoaXMgY2xhc3MgaXMgYXV0byBnZW5lcmF0ZWQgYnkgdGhlIHN3YWdnZXIgY29kZSBnZW5lcmF0b3IgcHJvZ3JhbS5cclxuICogaHR0cHM6Ly9naXRodWIuY29tL3N3YWdnZXItYXBpL3N3YWdnZXItY29kZWdlbi5naXRcclxuICogRG8gbm90IGVkaXQgdGhlIGNsYXNzIG1hbnVhbGx5LlxyXG4gKi9cclxuXHJcbmltcG9ydCAqIGFzIG1vZGVscyBmcm9tICcuL21vZGVscyc7XHJcblxyXG5leHBvcnQgaW50ZXJmYWNlIERhaWx5TWVudUVkaXQge1xyXG4gICAgZm9vZHM/OiBBcnJheTxtb2RlbHMuRGFpbHlNZW51c0Zvb2RzPjtcclxuXHJcbiAgICBsYXN0RWRpdD86IG1vZGVscy5MYXN0RWRpdDtcclxuXHJcbiAgICBkYXRlPzogRGF0ZTtcclxuXHJcbn1cclxuIl19