"use strict";
/**
 * Yum Food Orders
 * **Yum application, order food daily from the best chef in town**  This API is used by the angular.io client, and is not meant to be used otherwise.  Find source code of this API [here](http://gitlab/)  Copyright (C) 2017 JR Technologies.     ------------------------------------       Last edit: 21/04/2017 15:00   -------------------------------------
 *
 * OpenAPI spec version: 1.0.7
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiRm9vZERldGFpbHMuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJGb29kRGV0YWlscy50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRyIsInNvdXJjZXNDb250ZW50IjpbIi8qKlxyXG4gKiBZdW0gRm9vZCBPcmRlcnNcclxuICogKipZdW0gYXBwbGljYXRpb24sIG9yZGVyIGZvb2QgZGFpbHkgZnJvbSB0aGUgYmVzdCBjaGVmIGluIHRvd24qKiAgVGhpcyBBUEkgaXMgdXNlZCBieSB0aGUgYW5ndWxhci5pbyBjbGllbnQsIGFuZCBpcyBub3QgbWVhbnQgdG8gYmUgdXNlZCBvdGhlcndpc2UuICBGaW5kIHNvdXJjZSBjb2RlIG9mIHRoaXMgQVBJIFtoZXJlXShodHRwOi8vZ2l0bGFiLykgIENvcHlyaWdodCAoQykgMjAxNyBKUiBUZWNobm9sb2dpZXMuICAgICAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0gICAgICAgTGFzdCBlZGl0OiAyMS8wNC8yMDE3IDE1OjAwICAgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSBcclxuICpcclxuICogT3BlbkFQSSBzcGVjIHZlcnNpb246IDEuMC43XHJcbiAqIFxyXG4gKlxyXG4gKiBOT1RFOiBUaGlzIGNsYXNzIGlzIGF1dG8gZ2VuZXJhdGVkIGJ5IHRoZSBzd2FnZ2VyIGNvZGUgZ2VuZXJhdG9yIHByb2dyYW0uXHJcbiAqIGh0dHBzOi8vZ2l0aHViLmNvbS9zd2FnZ2VyLWFwaS9zd2FnZ2VyLWNvZGVnZW4uZ2l0XHJcbiAqIERvIG5vdCBlZGl0IHRoZSBjbGFzcyBtYW51YWxseS5cclxuICovXHJcblxyXG5pbXBvcnQgKiBhcyBtb2RlbHMgZnJvbSAnLi9tb2RlbHMnO1xyXG5cclxuZXhwb3J0IGludGVyZmFjZSBGb29kRGV0YWlscyB7XHJcbiAgICBmb29kTmFtZT86IHN0cmluZztcclxuXHJcbiAgICBmb29kVHlwZT86IHN0cmluZztcclxuXHJcbiAgICBkZXNjcmlwdGlvbj86IHN0cmluZztcclxuXHJcbiAgICBwcmljZT86IG51bWJlcjtcclxuXHJcbiAgICBzdGFuZGFyZD86IGJvb2xlYW47XHJcbn1cclxuIl19