"use strict";
/**
 * Yum Food Orders
 * **Yum application, order food daily from the best chef in town**  This API is used by the angular.io client, and is not meant to be used otherwise.  Find source code of this API [here](http://gitlab/)  Copyright (C) 2017 JR Technologies.     ------------------------------------       Last edit: 21/04/2017 15:00   -------------------------------------
 *
 * OpenAPI spec version: 1.0.7
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiRm9vZFdpdGhTdGF0cy5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIkZvb2RXaXRoU3RhdHMudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBOzs7Ozs7Ozs7O0dBVUciLCJzb3VyY2VzQ29udGVudCI6WyIvKipcclxuICogWXVtIEZvb2QgT3JkZXJzXHJcbiAqICoqWXVtIGFwcGxpY2F0aW9uLCBvcmRlciBmb29kIGRhaWx5IGZyb20gdGhlIGJlc3QgY2hlZiBpbiB0b3duKiogIFRoaXMgQVBJIGlzIHVzZWQgYnkgdGhlIGFuZ3VsYXIuaW8gY2xpZW50LCBhbmQgaXMgbm90IG1lYW50IHRvIGJlIHVzZWQgb3RoZXJ3aXNlLiAgRmluZCBzb3VyY2UgY29kZSBvZiB0aGlzIEFQSSBbaGVyZV0oaHR0cDovL2dpdGxhYi8pICBDb3B5cmlnaHQgKEMpIDIwMTcgSlIgVGVjaG5vbG9naWVzLiAgICAgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tICAgICAgIExhc3QgZWRpdDogMjEvMDQvMjAxNyAxNTowMCAgIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0gXHJcbiAqXHJcbiAqIE9wZW5BUEkgc3BlYyB2ZXJzaW9uOiAxLjAuN1xyXG4gKiBcclxuICpcclxuICogTk9URTogVGhpcyBjbGFzcyBpcyBhdXRvIGdlbmVyYXRlZCBieSB0aGUgc3dhZ2dlciBjb2RlIGdlbmVyYXRvciBwcm9ncmFtLlxyXG4gKiBodHRwczovL2dpdGh1Yi5jb20vc3dhZ2dlci1hcGkvc3dhZ2dlci1jb2RlZ2VuLmdpdFxyXG4gKiBEbyBub3QgZWRpdCB0aGUgY2xhc3MgbWFudWFsbHkuXHJcbiAqL1xyXG5cclxuaW1wb3J0ICogYXMgbW9kZWxzIGZyb20gJy4vbW9kZWxzJztcclxuXHJcbi8qKlxyXG4gKiBGb29kLCBzdGF0aXN0aWNzICBpbmNsdWRlZCBEVE9cclxuICovXHJcbmV4cG9ydCBpbnRlcmZhY2UgRm9vZFdpdGhTdGF0cyB7XHJcbiAgICBmb29kSXRlbT86IG1vZGVscy5Gb29kO1xyXG5cclxuICAgIHN0YXRzPzogeyBba2V5OiBzdHJpbmddOiBtb2RlbHMuU3RhdGlzdGljOyB9O1xyXG5cclxuICAgIGVkaXRhYmxlPzogYm9vbGVhbjtcclxuXHJcbiAgICBsYXN0RWRpdD86IG1vZGVscy5MYXN0RWRpdDtcclxuXHJcbn1cclxuIl19