"use strict";
/**
 * Yum Food Orders
 * **Yum application, order food daily from the best chef in town**  This API is used by the angular.io client, and is not meant to be used otherwise.  Find source code of this API [here](https://github.com/jrtdev/yum)  Copyright (C) 2017 JR Technologies.     ------------------------------------      Last edit: 28/09/2017 10:00  -------------------------------------
 *
 * OpenAPI spec version: 1.2.8
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiUmVmcmVzaC5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIlJlZnJlc2gudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBOzs7Ozs7Ozs7O0dBVUciLCJzb3VyY2VzQ29udGVudCI6WyIvKipcclxuICogWXVtIEZvb2QgT3JkZXJzXHJcbiAqICoqWXVtIGFwcGxpY2F0aW9uLCBvcmRlciBmb29kIGRhaWx5IGZyb20gdGhlIGJlc3QgY2hlZiBpbiB0b3duKiogIFRoaXMgQVBJIGlzIHVzZWQgYnkgdGhlIGFuZ3VsYXIuaW8gY2xpZW50LCBhbmQgaXMgbm90IG1lYW50IHRvIGJlIHVzZWQgb3RoZXJ3aXNlLiAgRmluZCBzb3VyY2UgY29kZSBvZiB0aGlzIEFQSSBbaGVyZV0oaHR0cHM6Ly9naXRodWIuY29tL2pydGRldi95dW0pICBDb3B5cmlnaHQgKEMpIDIwMTcgSlIgVGVjaG5vbG9naWVzLiAgICAgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tICAgICAgTGFzdCBlZGl0OiAyOC8wOS8yMDE3IDEwOjAwICAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tIFxyXG4gKlxyXG4gKiBPcGVuQVBJIHNwZWMgdmVyc2lvbjogMS4yLjhcclxuICogXHJcbiAqXHJcbiAqIE5PVEU6IFRoaXMgY2xhc3MgaXMgYXV0byBnZW5lcmF0ZWQgYnkgdGhlIHN3YWdnZXIgY29kZSBnZW5lcmF0b3IgcHJvZ3JhbS5cclxuICogaHR0cHM6Ly9naXRodWIuY29tL3N3YWdnZXItYXBpL3N3YWdnZXItY29kZWdlbi5naXRcclxuICogRG8gbm90IGVkaXQgdGhlIGNsYXNzIG1hbnVhbGx5LlxyXG4gKi9cclxuXHJcbmltcG9ydCAqIGFzIG1vZGVscyBmcm9tICcuL21vZGVscyc7XHJcblxyXG4vKipcclxuICogYXV0aCB0b2tlblxyXG4gKi9cclxuZXhwb3J0IGludGVyZmFjZSBSZWZyZXNoIHtcclxuICAgIHRva2VuPzogc3RyaW5nO1xyXG5cclxuICAgIGJhbGFuY2U/OiBudW1iZXI7XHJcblxyXG59XHJcbiJdfQ==