"use strict";
/**
 * Yum Food Orders
 * **Yum application, order food daily from the best chef in town**  This API is used by the angular.io client, and is not meant to be used otherwise.  Find source code of this API [here](http://gitlab/)  Copyright (C) 2017 JR Technologies.     ------------------------------------       Last edit: 21/04/2017 15:00   -------------------------------------
 *
 * OpenAPI spec version: 1.0.7
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiU3RhdGlzdGljLmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiU3RhdGlzdGljLnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQTs7Ozs7Ozs7OztHQVVHIiwic291cmNlc0NvbnRlbnQiOlsiLyoqXHJcbiAqIFl1bSBGb29kIE9yZGVyc1xyXG4gKiAqKll1bSBhcHBsaWNhdGlvbiwgb3JkZXIgZm9vZCBkYWlseSBmcm9tIHRoZSBiZXN0IGNoZWYgaW4gdG93bioqICBUaGlzIEFQSSBpcyB1c2VkIGJ5IHRoZSBhbmd1bGFyLmlvIGNsaWVudCwgYW5kIGlzIG5vdCBtZWFudCB0byBiZSB1c2VkIG90aGVyd2lzZS4gIEZpbmQgc291cmNlIGNvZGUgb2YgdGhpcyBBUEkgW2hlcmVdKGh0dHA6Ly9naXRsYWIvKSAgQ29weXJpZ2h0IChDKSAyMDE3IEpSIFRlY2hub2xvZ2llcy4gICAgIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSAgICAgICBMYXN0IGVkaXQ6IDIxLzA0LzIwMTcgMTU6MDAgICAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tXHJcbiAqXHJcbiAqIE9wZW5BUEkgc3BlYyB2ZXJzaW9uOiAxLjAuN1xyXG4gKlxyXG4gKlxyXG4gKiBOT1RFOiBUaGlzIGNsYXNzIGlzIGF1dG8gZ2VuZXJhdGVkIGJ5IHRoZSBzd2FnZ2VyIGNvZGUgZ2VuZXJhdG9yIHByb2dyYW0uXHJcbiAqIGh0dHBzOi8vZ2l0aHViLmNvbS9zd2FnZ2VyLWFwaS9zd2FnZ2VyLWNvZGVnZW4uZ2l0XHJcbiAqIERvIG5vdCBlZGl0IHRoZSBjbGFzcyBtYW51YWxseS5cclxuICovXHJcblxyXG5pbXBvcnQgKiBhcyBtb2RlbHMgZnJvbSAnLi9tb2RlbHMnO1xyXG5cclxuLyoqXHJcbiAqIEZvb2Qgc3RhdGlzdGljc1xyXG4gKi9cclxuZXhwb3J0IGludGVyZmFjZSBTdGF0aXN0aWMge1xyXG4gIHdlZWs/OiBudW1iZXI7XHJcblxyXG4gIHF1YW50aXR5PzogbnVtYmVyO1xyXG5cclxufVxyXG4iXX0=