"use strict";
/**
 * Yum Food Orders
 * **Yum application, order food daily from the best chef in town**  This API is used by the angular.io client, and is not meant to be used otherwise.  Find source code of this API [here](http://gitlab/)  Copyright (C) 2017 JR Technologies.     ------------------------------------       Last edit: 21/04/2017 15:00   -------------------------------------
 *
 * OpenAPI spec version: 1.0.7
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiVG9rZW4uanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJUb2tlbi50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRyIsInNvdXJjZXNDb250ZW50IjpbIi8qKlxyXG4gKiBZdW0gRm9vZCBPcmRlcnNcclxuICogKipZdW0gYXBwbGljYXRpb24sIG9yZGVyIGZvb2QgZGFpbHkgZnJvbSB0aGUgYmVzdCBjaGVmIGluIHRvd24qKiAgVGhpcyBBUEkgaXMgdXNlZCBieSB0aGUgYW5ndWxhci5pbyBjbGllbnQsIGFuZCBpcyBub3QgbWVhbnQgdG8gYmUgdXNlZCBvdGhlcndpc2UuICBGaW5kIHNvdXJjZSBjb2RlIG9mIHRoaXMgQVBJIFtoZXJlXShodHRwOi8vZ2l0bGFiLykgIENvcHlyaWdodCAoQykgMjAxNyBKUiBUZWNobm9sb2dpZXMuICAgICAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0gICAgICAgTGFzdCBlZGl0OiAyMS8wNC8yMDE3IDE1OjAwICAgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLVxyXG4gKlxyXG4gKiBPcGVuQVBJIHNwZWMgdmVyc2lvbjogMS4wLjdcclxuICpcclxuICpcclxuICogTk9URTogVGhpcyBjbGFzcyBpcyBhdXRvIGdlbmVyYXRlZCBieSB0aGUgc3dhZ2dlciBjb2RlIGdlbmVyYXRvciBwcm9ncmFtLlxyXG4gKiBodHRwczovL2dpdGh1Yi5jb20vc3dhZ2dlci1hcGkvc3dhZ2dlci1jb2RlZ2VuLmdpdFxyXG4gKiBEbyBub3QgZWRpdCB0aGUgY2xhc3MgbWFudWFsbHkuXHJcbiAqL1xyXG5cclxuaW1wb3J0ICogYXMgbW9kZWxzIGZyb20gJy4vbW9kZWxzJztcclxuXHJcbi8qKlxyXG4gKiBhdXRoIHRva2VuXHJcbiAqL1xyXG5leHBvcnQgaW50ZXJmYWNlIFRva2VuIHtcclxuICAgIHRva2VuPzogc3RyaW5nO1xyXG5cclxuICAgIHVzZXI/OiBtb2RlbHMuVXNlcjtcclxufVxyXG4iXX0=