"use strict";
/**
 * Yum Food Orders
 * **Yum application, order food daily from the best chef in town**  This API is used by the angular.io client, and is not meant to be used otherwise.  Find source code of this API [here](https://github.com/jrtdev/yum)  Copyright (C) 2017 JR Technologies.     ------------------------------------      Last edit: 28/09/2017 10:00  -------------------------------------
 *
 * OpenAPI spec version: 1.2.8
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiVHJhbnNhY3Rpb24uanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJUcmFuc2FjdGlvbi50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7Ozs7R0FVRyIsInNvdXJjZXNDb250ZW50IjpbIi8qKlxyXG4gKiBZdW0gRm9vZCBPcmRlcnNcclxuICogKipZdW0gYXBwbGljYXRpb24sIG9yZGVyIGZvb2QgZGFpbHkgZnJvbSB0aGUgYmVzdCBjaGVmIGluIHRvd24qKiAgVGhpcyBBUEkgaXMgdXNlZCBieSB0aGUgYW5ndWxhci5pbyBjbGllbnQsIGFuZCBpcyBub3QgbWVhbnQgdG8gYmUgdXNlZCBvdGhlcndpc2UuICBGaW5kIHNvdXJjZSBjb2RlIG9mIHRoaXMgQVBJIFtoZXJlXShodHRwczovL2dpdGh1Yi5jb20vanJ0ZGV2L3l1bSkgIENvcHlyaWdodCAoQykgMjAxNyBKUiBUZWNobm9sb2dpZXMuICAgICAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0gICAgICBMYXN0IGVkaXQ6IDI4LzA5LzIwMTcgMTA6MDAgIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0gXHJcbiAqXHJcbiAqIE9wZW5BUEkgc3BlYyB2ZXJzaW9uOiAxLjIuOFxyXG4gKiBcclxuICpcclxuICogTk9URTogVGhpcyBjbGFzcyBpcyBhdXRvIGdlbmVyYXRlZCBieSB0aGUgc3dhZ2dlciBjb2RlIGdlbmVyYXRvciBwcm9ncmFtLlxyXG4gKiBodHRwczovL2dpdGh1Yi5jb20vc3dhZ2dlci1hcGkvc3dhZ2dlci1jb2RlZ2VuLmdpdFxyXG4gKiBEbyBub3QgZWRpdCB0aGUgY2xhc3MgbWFudWFsbHkuXHJcbiAqL1xyXG5cclxuaW1wb3J0ICogYXMgbW9kZWxzIGZyb20gJy4vbW9kZWxzJztcclxuXHJcbi8qKlxyXG4gKiBUcmFuc2FjdGlvbiB3aXRoIGJhbGFuY2VcclxuICovXHJcbmV4cG9ydCBpbnRlcmZhY2UgVHJhbnNhY3Rpb24ge1xyXG4gICAgYW1vdW50PzogbnVtYmVyO1xyXG5cclxuICAgIGJhbGFuY2U/OiBudW1iZXI7XHJcblxyXG4gICAgZGF0ZXRpbWU/OiBEYXRlO1xyXG5cclxuICAgIGZpcnN0TmFtZT86IHN0cmluZztcclxuXHJcbiAgICBsYXN0TmFtZT86IHN0cmluZztcclxuXHJcbiAgICBtZW51RGF0ZT86IERhdGU7XHJcblxyXG4gICAgb3JkZXJUeXBlPzogc3RyaW5nO1xyXG5cclxufVxyXG4iXX0=