"use strict";
/**
 * Yum Food Orders
 * **Yum application, order food daily from the best chef in town**  This API is used by the angular.io client, and is not meant to be used otherwise.  Find source code of this API [here](http://gitlab/)  Copyright (C) 2017 JR Technologies.     ------------------------------------       Last edit: 21/04/2017 15:00   -------------------------------------
 *
 * OpenAPI spec version: 1.0.7
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiVXNlcnNQYWdlLmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiVXNlcnNQYWdlLnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQTs7Ozs7Ozs7OztHQVVHIiwic291cmNlc0NvbnRlbnQiOlsiLyoqXHJcbiAqIFl1bSBGb29kIE9yZGVyc1xyXG4gKiAqKll1bSBhcHBsaWNhdGlvbiwgb3JkZXIgZm9vZCBkYWlseSBmcm9tIHRoZSBiZXN0IGNoZWYgaW4gdG93bioqICBUaGlzIEFQSSBpcyB1c2VkIGJ5IHRoZSBhbmd1bGFyLmlvIGNsaWVudCwgYW5kIGlzIG5vdCBtZWFudCB0byBiZSB1c2VkIG90aGVyd2lzZS4gIEZpbmQgc291cmNlIGNvZGUgb2YgdGhpcyBBUEkgW2hlcmVdKGh0dHA6Ly9naXRsYWIvKSAgQ29weXJpZ2h0IChDKSAyMDE3IEpSIFRlY2hub2xvZ2llcy4gICAgIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSAgICAgICBMYXN0IGVkaXQ6IDIxLzA0LzIwMTcgMTU6MDAgICAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tIFxyXG4gKlxyXG4gKiBPcGVuQVBJIHNwZWMgdmVyc2lvbjogMS4wLjdcclxuICogXHJcbiAqXHJcbiAqIE5PVEU6IFRoaXMgY2xhc3MgaXMgYXV0byBnZW5lcmF0ZWQgYnkgdGhlIHN3YWdnZXIgY29kZSBnZW5lcmF0b3IgcHJvZ3JhbS5cclxuICogaHR0cHM6Ly9naXRodWIuY29tL3N3YWdnZXItYXBpL3N3YWdnZXItY29kZWdlbi5naXRcclxuICogRG8gbm90IGVkaXQgdGhlIGNsYXNzIG1hbnVhbGx5LlxyXG4gKi9cclxuXHJcbmltcG9ydCAqIGFzIG1vZGVscyBmcm9tICcuL21vZGVscyc7XHJcblxyXG5leHBvcnQgaW50ZXJmYWNlIFVzZXJzUGFnZSB7XHJcbiAgICB1c2Vycz86IEFycmF5PG1vZGVscy5Vc2VyPjtcclxuXHJcbiAgICB0b3RhbEVsZW1lbnRzPzogbnVtYmVyO1xyXG5cclxuICAgIHRvdGFsUGFnZXM/OiBudW1iZXI7XHJcblxyXG59XHJcbiJdfQ==