"use strict";
/**
 * Yum Food Orders
 * **Yum application, order food daily from the best chef in town**  This API is used by the angular.io client, and is not meant to be used otherwise.  Find source code of this API [here](http://gitlab/)  Copyright (C) 2017 JR Technologies.     ------------------------------------       Last edit: 21/04/2017 15:00   -------------------------------------
 *
 * OpenAPI spec version: 1.0.7
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiVXNlci5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIlVzZXIudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBOzs7Ozs7Ozs7O0dBVUciLCJzb3VyY2VzQ29udGVudCI6WyIvKipcclxuICogWXVtIEZvb2QgT3JkZXJzXHJcbiAqICoqWXVtIGFwcGxpY2F0aW9uLCBvcmRlciBmb29kIGRhaWx5IGZyb20gdGhlIGJlc3QgY2hlZiBpbiB0b3duKiogIFRoaXMgQVBJIGlzIHVzZWQgYnkgdGhlIGFuZ3VsYXIuaW8gY2xpZW50LCBhbmQgaXMgbm90IG1lYW50IHRvIGJlIHVzZWQgb3RoZXJ3aXNlLiAgRmluZCBzb3VyY2UgY29kZSBvZiB0aGlzIEFQSSBbaGVyZV0oaHR0cDovL2dpdGxhYi8pICBDb3B5cmlnaHQgKEMpIDIwMTcgSlIgVGVjaG5vbG9naWVzLiAgICAgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tICAgICAgIExhc3QgZWRpdDogMjEvMDQvMjAxNyAxNTowMCAgIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS1cclxuICpcclxuICogT3BlbkFQSSBzcGVjIHZlcnNpb246IDEuMC43XHJcbiAqXHJcbiAqXHJcbiAqIE5PVEU6IFRoaXMgY2xhc3MgaXMgYXV0byBnZW5lcmF0ZWQgYnkgdGhlIHN3YWdnZXIgY29kZSBnZW5lcmF0b3IgcHJvZ3JhbS5cclxuICogaHR0cHM6Ly9naXRodWIuY29tL3N3YWdnZXItYXBpL3N3YWdnZXItY29kZWdlbi5naXRcclxuICogRG8gbm90IGVkaXQgdGhlIGNsYXNzIG1hbnVhbGx5LlxyXG4gKi9cclxuXHJcbmltcG9ydCAqIGFzIG1vZGVscyBmcm9tICcuL21vZGVscyc7XHJcblxyXG4vKipcclxuICogVXNlciBEVE9cclxuICovXHJcbmV4cG9ydCBpbnRlcmZhY2UgVXNlciB7XHJcbiAgICBpZD86IG51bWJlcjtcclxuXHJcbiAgICBsYXN0TmFtZT86IHN0cmluZztcclxuXHJcbiAgICBmaXJzdE5hbWU/OiBzdHJpbmc7XHJcblxyXG4gICAgZW1haWw/OiBzdHJpbmc7XHJcblxyXG4gICAgdXNlck5hbWU/OiBzdHJpbmc7XHJcblxyXG4gICAgcm9sZT86IHN0cmluZztcclxuXHJcbiAgICByZWdpc3RyYXRpb25EYXRlPzogRGF0ZTtcclxuXHJcbiAgICBhcHByb3ZlZD86IGJvb2xlYW47XHJcblxyXG4gICAgbGFzdEVkaXQ/OiBtb2RlbHMuTGFzdEVkaXQ7XHJcblxyXG4gICAgaGFzUGljdHVyZT86IGJvb2xlYW47XHJcblxyXG4gICAgYmFsYW5jZT86IG51bWJlcjtcclxuXHJcbiAgICBvcmRlck50Zj86IGJvb2xlYW47XHJcblxyXG4gICAgb3JkZXJNb2RpZnlOdGY/OiBib29sZWFuO1xyXG5cclxuICAgIGFkbWluT3JkZXJOdGY/OiBib29sZWFuO1xyXG5cclxuICAgIGFkbWluT3JkZXJNb2RpZnlOdGY/OiBib29sZWFuO1xyXG5cclxuICAgIGJhbGFuY2VOdGY/OiBib29sZWFuO1xyXG5cclxufVxyXG4iXX0=